header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: thumbrise
    copyright-year: '2026'
    software-name: op-universal-vendor-http-php

  paths:
    - '**/*.php'

  comment: on-failure
  license-location-threshold: 80
