<?php

/*
 * Copyright 2026 thumbrise
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

use PhpCsFixer\Config;
use PhpCsFixer\Finder;

$finder = (new Finder())
    ->in(__DIR__)
    ->path([
        'src',
        '.php-cs-fixer.dist.php',
    ])
    ->ignoreDotFiles(false)
    ->notPath('cache')
;

return (new Config())
    ->setRules([
        'encoding'                                => true,
        'full_opening_tag'                        => true,
        'constant_case'                           => ['case' => 'lower'],
        'control_structure_braces'                => true,
        'control_structure_continuation_position' => ['position' => 'same_line'],
        'elseif'                                  => true,
        'indentation_type'                        => true,
        'line_ending'                             => true,
        'lowercase_keywords'                      => true,
        'no_break_comment'                        => ['comment_text' => 'no break'],
        'no_closing_tag'                          => true,
        'no_multiple_statements_per_line'         => true,
        'no_space_around_double_colon'            => true,
        'no_spaces_after_function_name'           => true,
        'no_trailing_whitespace'                  => true,
        'no_trailing_whitespace_in_comment'       => true,
        'single_blank_line_at_eof'                => true,
        'single_line_after_imports'               => true,
        'spaces_inside_parentheses'               => ['space' => 'none'],
        'switch_case_semicolon_to_colon'          => true,
        'switch_case_space'                       => true,
        'blank_line_after_opening_tag'            => true,
        'blank_line_between_import_groups'        => true,
        'blank_lines_before_namespace'            => [
            'max_line_breaks' => 2,
            'min_line_breaks' => 2,
        ],
        'compact_nullable_type_declaration'  => true,
        'declare_equal_normalize'            => true,
        'lowercase_cast'                     => true,
        'lowercase_static_reference'         => true,
        'no_blank_lines_after_class_opening' => true,
        'no_leading_import_slash'            => true,
        'no_whitespace_in_blank_line'        => true,
        'return_type_declaration'            => true,
        'short_scalar_cast'                  => true,
        'single_trait_insert_per_statement'  => true,
        'ternary_operator_spaces'            => true,
        'visibility_required'                => true,
        'cast_spaces'                        => true,
        'align_multiline_comment'            => true,
        'backtick_to_shell_exec'             => true,
        'braces_position'                    => [
            'allow_single_line_anonymous_functions'     => true,
            'allow_single_line_empty_anonymous_classes' => true,
            'anonymous_classes_opening_brace'           => 'same_line',
            'anonymous_functions_opening_brace'         => 'same_line',
            'classes_opening_brace'                     => 'next_line_unless_newline_at_signature_end',
            'control_structures_opening_brace'          => 'same_line',
            'functions_opening_brace'                   => 'next_line_unless_newline_at_signature_end',
        ],
        'class_attributes_separation' => true,
        'class_definition'            => [
            'inline_constructor_arguments'        => true,
            'multi_line_extends_each_single_line' => false,
            'single_item_single_line'             => false,
            'single_line'                         => true,
            'space_before_parenthesis'            => false,
        ],
        'class_reference_name_casing' => true,
        'clean_namespace'             => true,
        'declare_parentheses'         => true,
        'echo_tag_syntax'             => true,
        'empty_loop_condition'        => true,
        'function_declaration'        => [
            'closure_fn_spacing'         => 'one',
            'closure_function_spacing'   => 'one',
            'trailing_comma_single_line' => false,
        ],
        'general_phpdoc_tag_rename'                        => true,
        'include'                                          => true,
        'increment_style'                                  => true,
        'integer_literal_case'                             => true,
        'lambda_not_used_import'                           => true,
        'linebreak_after_opening_tag'                      => true,
        'magic_constant_casing'                            => true,
        'magic_method_casing'                              => true,
        'native_function_casing'                           => true,
        'native_type_declaration_casing'                   => true,
        'no_alias_language_construct_call'                 => true,
        'no_alternative_syntax'                            => true,
        'no_binary_string'                                 => true,
        'no_blank_lines_after_phpdoc'                      => true,
        'no_empty_comment'                                 => true,
        'no_empty_phpdoc'                                  => true,
        'no_empty_statement'                               => true,
        'no_leading_namespace_whitespace'                  => true,
        'no_mixed_echo_print'                              => true,
        'no_multiline_whitespace_around_double_arrow'      => true,
        'no_null_property_initialization'                  => true,
        'no_short_bool_cast'                               => true,
        'no_singleline_whitespace_before_semicolons'       => true,
        'no_spaces_around_offset'                          => true,
        'no_trailing_comma_in_singleline'                  => true,
        'no_unneeded_braces'                               => true,
        'no_unneeded_import_alias'                         => true,
        'no_unset_cast'                                    => true,
        'no_useless_concat_operator'                       => true,
        'no_useless_nullsafe_operator'                     => true,
        'normalize_index_brace'                            => true,
        'nullable_type_declaration'                        => true,
        'nullable_type_declaration_for_default_null_value' => true,
        'object_operator_without_whitespace'               => true,
        'operator_linebreak'                               => ['only_booleans' => true],
        'ordered_imports'                                  => [
            'imports_order'  => ['class', 'function', 'const'],
            'sort_algorithm' => 'alpha',
        ],
        'php_unit_fqcn_annotation'     => true,
        'php_unit_method_casing'       => true,
        'phpdoc_align'                 => true,
        'phpdoc_indent'                => true,
        'phpdoc_inline_tag_normalizer' => true,
        'phpdoc_no_access'             => true,
        'phpdoc_no_alias_tag'          => true,
        'phpdoc_no_package'            => true,
        'phpdoc_no_useless_inheritdoc' => true,
        'phpdoc_order'                 => ['order' => ['param', 'return', 'throws']],
        'phpdoc_return_self_reference' => true,
        'phpdoc_scalar'                => true,
        'phpdoc_separation'            => [
            'groups' => [
                ['Annotation', 'NamedArgumentConstructor', 'Target'],
                ['author', 'copyright', 'license'],
                ['category', 'package', 'subpackage'],
                ['property', 'property-read', 'property-write'],
                ['deprecated', 'link', 'see', 'since'],
            ],
        ],
        'phpdoc_single_line_var_spacing'                => true,
        'phpdoc_summary'                                => true,
        'phpdoc_tag_type'                               => true,
        'phpdoc_to_comment'                             => true,
        'phpdoc_trim'                                   => true,
        'phpdoc_trim_consecutive_blank_line_separation' => true,
        'phpdoc_types'                                  => true,
        'phpdoc_var_without_name'                       => true,
        'semicolon_after_instruction'                   => true,
        'simple_to_complex_string_variable'             => true,
        'single_class_element_per_statement'            => true,
        'single_import_per_statement'                   => true,
        'single_line_comment_spacing'                   => true,
        'single_quote'                                  => true,
        'single_space_around_construct'                 => [
            'constructs_preceded_by_a_single_space' => [
                'as',
                'else',
                'elseif',
                'use_lambda',
            ],
        ],
        'space_after_semicolon'       => true,
        'standardize_increment'       => true,
        'standardize_not_equals'      => true,
        'statement_indentation'       => ['stick_comment_to_next_continuous_control_statement' => true],
        'switch_continue_to_break'    => true,
        'trim_array_spaces'           => true,
        'type_declaration_spaces'     => true,
        'types_spaces'                => ['space' => 'single'],
        'unary_operator_spaces'       => true,
        'yoda_style'                  => true,
        'blank_line_before_statement' => [
            'statements' => [
                'break',
                'case',
                'continue',
                'declare',
                'default',
                'exit',
                'goto',
                'include',
                'include_once',
                'phpdoc',
                'require',
                'require_once',
                'return',
                'switch',
                'throw',
                'try',
                'yield',
                'yield_from',
            ],
        ],
        'combine_consecutive_issets'   => true,
        'combine_consecutive_unsets'   => true,
        'empty_loop_body'              => ['style' => 'semicolon'],
        'explicit_indirect_variable'   => true,
        'explicit_string_variable'     => true,
        'fully_qualified_strict_types' => ['import_symbols' => true],
        'heredoc_to_nowdoc'            => true,
        'method_argument_space'        => [
            'after_heredoc'                    => false,
            'attribute_placement'              => 'standalone',
            'keep_multiple_spaces_after_comma' => false,
            'on_multiline'                     => 'ensure_fully_multiline',
        ],
        'method_chaining_indentation'            => true,
        'multiline_comment_opening_closing'      => true,
        'multiline_whitespace_before_semicolons' => [
            'strategy' => 'new_line_for_chained_calls',
        ],
        'no_extra_blank_lines' => [
            'tokens' => ['attribute', 'break', 'case', 'continue', 'curly_brace_block', 'default', 'extra', 'parenthesis_brace_block', 'return', 'square_brace_block', 'switch', 'throw', 'use'],
        ],
        'no_superfluous_elseif'           => true,
        'no_superfluous_phpdoc_tags'      => true,
        'no_unneeded_control_parentheses' => [
            'statements' => ['break', 'clone', 'continue', 'echo_print', 'negative_instanceof', 'others', 'return', 'switch_case', 'yield', 'yield_from'],
        ],
        'no_useless_else'                     => true,
        'no_useless_return'                   => true,
        'no_whitespace_before_comma_in_array' => true,
        'ordered_class_elements'              => true,
        'ordered_types'                       => true,
        'php_unit_internal_class'             => true,
        'phpdoc_add_missing_param_annotation' => false,
        'phpdoc_no_empty_return'              => true,
        'phpdoc_order_by_value'               => true,
        'phpdoc_types_order'                  => true,
        'phpdoc_var_annotation_correct_order' => true,
        'protected_to_private'                => true,
        'return_assignment'                   => true,
        'self_static_accessor'                => true,
        'single_line_comment_style'           => true,
        'single_line_empty_body'              => true,
        'single_line_throw'                   => false,
        'string_implicit_backslashes'         => true,
        'trailing_comma_in_multiline'         => [
            'after_heredoc' => true,
            'elements'      => [
                'arguments',
                'array_destructuring',
                'arrays',
                'match',
                'parameters',
            ],
        ],
        'whitespace_after_comma_in_array' => [
            'ensure_single_space' => true,
        ],
        'array_syntax' => [
            'syntax' => 'short',
        ],
        'array_indentation'      => true,
        'binary_operator_spaces' => [
            'default' => 'align_single_space_minimal',
        ],
        'concat_space' => [
            'spacing' => 'one',
        ],
        'new_with_parentheses' => [
            'anonymous_class' => false,
        ],
        'not_operator_with_successor_space' => true,
        'global_namespace_import'           => [
            'import_classes'   => true,
            'import_constants' => true,
            'import_functions' => true,
        ],
        'php_unit_test_class_requires_covers' => true,
        'no_unused_imports'                   => true,
    ])
    ->setFinder($finder)
;
